### ISSUE TITLE
pretrained models

### ISSUE THREAD

**Issue by wenqingchu** [zhixinshu/DeformingAutoencoders-pytorch#1]
Hi, 
Thanks for your amazing work. Would you like to provide some pretrained models on faces so that we can play with it directly?

**Comment by zhixinshu** [comment]
Please find some checkpoints at:
https://drive.google.com/drive/folders/1A2Qj1NhzVU5XSjeilKhjWwAgNWvlRyuA?usp=sharing
Details of the checkpoints is added in readme as well.
