### ISSUE TITLE
Could you kindly explain how you chose the parameter for integrator?

### ISSUE THREAD

**Issue by pxiangwu** [zhixinshu/DeformingAutoencoders-pytorch#4]
Hi, thank you for the helpful code.

In this following code, I wonder why you chose this parameter "1.2"? Is there any motivation?
https://github.com/zhixinshu/DeformingAutoencoders-pytorch/blob/master/DAENet.py#L484

`self.warping = self.integrator(self.diffentialWarping)-1.2`

Is this parameter introduced so that parts of the deformation fields could be of negative value?
And is the model performance sensitive to this number?

Thanks so much.

**Comment by pxiangwu** [comment]
I think I got the answer. Thanks any way.

**Comment by xwjabc** [comment]
@pxiangwu Could you explain a bit to me about why 1.2 is used here? I still did not get it.

**Comment by RegisWu** [comment]
Hi @zhixinshu, @pxiangwu and @xwjabc

I am also curious about why we need to subtract 1.2 in the integrator, is it used as a kind of normalization? Could you please explain more?

Thanks!
